"""create_unique_constraints

Revision ID: 0011
Revises: 0010
Create Date: 2024-12-01 15:58:59.157318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0011'
down_revision: Union[str, None] = '0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bot_configs', ['id'])
    op.create_unique_constraint(None, 'custom_commands', ['id'])
    op.create_unique_constraint(None, 'dice_rolls', ['id'])
    op.create_unique_constraint(None, 'gw2_configs', ['id'])
    op.create_unique_constraint(None, 'gw2_keys', ['id'])
    op.create_unique_constraint(None, 'gw2_session_chars', ['id'])
    op.create_unique_constraint(None, 'gw2_sessions', ['id'])
    op.create_unique_constraint(None, 'profanity_filters', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profanity_filters', type_='unique')
    op.drop_constraint(None, 'gw2_sessions', type_='unique')
    op.drop_constraint(None, 'gw2_session_chars', type_='unique')
    op.drop_constraint(None, 'gw2_keys', type_='unique')
    op.drop_constraint(None, 'gw2_configs', type_='unique')
    op.drop_constraint(None, 'dice_rolls', type_='unique')
    op.drop_constraint(None, 'custom_commands', type_='unique')
    op.drop_constraint(None, 'bot_configs', type_='unique')
    # ### end Alembic commands ###
