"""create_gw2_chars_start

Revision ID: 11
Revises: 10
Create Date: 2023-11-13 18:13:37.637510

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11'
down_revision: Union[str, None] = '10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'gw2_chars_start',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('profession', sa.String(), nullable=False),
        sa.Column('deaths', sa.Integer(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('name')
        )
    op.create_unique_constraint('gw2_chars_start_id_key', 'gw2_chars_start', ['id'])
    op.execute("""
        CREATE TRIGGER before_update_gw2_chars_start_tr
            BEFORE UPDATE ON gw2_chars_start
            FOR EACH ROW
            EXECUTE PROCEDURE updated_at_column_func();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TRIGGER IF EXISTS before_update_gw2_chars_start_tr ON bot_configs')
    op.drop_constraint('gw2_chars_start_id_key', 'gw2_chars_start', type_='unique')
    op.drop_table('gw2_chars_start')
    # ### end Alembic commands ###
