"""create_gw2_chars_end

Revision ID: 14
Revises: 13
Create Date: 2023-11-13 18:16:10.290442

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14'
down_revision: Union[str, None] = '13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gw2_chars_end',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('profession', sa.String(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_unique_constraint(None, 'gw2_chars_end', ['id'])
    op.execute("""
        CREATE TRIGGER before_update_gw2_chars_end_tr
            BEFORE UPDATE ON gw2_chars_end
            FOR EACH ROW
            EXECUTE PROCEDURE updated_at_column_func();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TRIGGER IF EXISTS before_update_gw2_chars_end_tr ON bot_configs')
    op.drop_constraint(None, 'gw2_chars_end', type_='unique')
    op.drop_table('gw2_chars_end')
    # ### end Alembic commands ###
