"""create_blacklist

Revision ID: 8
Revises: 7
Create Date: 2023-11-12 17:55:53.983013

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8'
down_revision: Union[str, None] = '7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'blacklist', ['id'])
    op.create_index(op.f('ix_blacklist_server_id'), 'blacklist', ['server_id'], unique=False)
    op.create_index(op.f('ix_blacklist_user_id'), 'blacklist', ['user_id'], unique=False)
    op.execute("""
        CREATE TRIGGER before_update_blacklist_tr
            BEFORE UPDATE ON blacklist
            FOR EACH ROW
            EXECUTE PROCEDURE updated_at_column_func();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TRIGGER IF EXISTS before_update_blacklist_tr ON bot_configs')
    op.drop_index(op.f('ix_blacklist_user_id'), table_name='blacklist')
    op.drop_index(op.f('ix_blacklist_server_id'), table_name='blacklist')
    op.drop_constraint(None, 'blacklist', type_='unique')
    op.drop_table('blacklist')
    # ### end Alembic commands ###
