"""create_muted

Revision ID: 9
Revises: 8
Create Date: 2023-11-12 17:57:54.758353

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9'
down_revision: Union[str, None] = '8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muted',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'muted', ['id'])
    op.create_index(op.f('ix_muted_server_id'), 'muted', ['server_id'], unique=False)
    op.create_index(op.f('ix_muted_user_id'), 'muted', ['user_id'], unique=False)
    op.execute("""
        CREATE TRIGGER before_update_muted_tr
            BEFORE UPDATE ON muted
            FOR EACH ROW
            EXECUTE PROCEDURE updated_at_column_func();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TRIGGER IF EXISTS before_update_muted_tr ON bot_configs')
    op.drop_index(op.f('ix_muted_user_id'), table_name='muted')
    op.drop_index(op.f('ix_muted_server_id'), table_name='muted')
    op.drop_constraint(None, 'muted', type_='unique')
    op.drop_table('muted')
    # ### end Alembic commands ###
