sonar.projectKey=ddc_DiscordBot
sonar.organization=ddc1

sonar.sources=src
sonar.tests=tests

sonar.python.version=3.14
sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=\
  .github/**,\
  tests/**

sonar.coverage.exclusions=\
  .github/**/*,\
  tests/**/*