"""GW2 API currency and achievement ID mappings.

Wallet IDs from: https://api.guildwars2.com/v2/currencies?ids=all
Achievement IDs from: https://api.guildwars2.com/v2/achievements
"""

from typing import Final

# Mapping of GW2 API wallet currency IDs to internal stat names
WALLET_MAPPING: Final[dict[int, str]] = {
    1: "gold",
    2: "karma",
    3: "laurels",
    4: "gems",
    5: "ascalonian_tears",
    6: "shards_of_zhaitan",
    7: "fractal_relics",
    9: "seals_of_beetletun",
    10: "manifesto_of_the_moletariate",
    11: "deadly_blooms",
    12: "symbols_of_koda",
    13: "flame_legion_charr_carvings",
    14: "knowledge_crystals",
    15: "badges_honor",
    16: "guild_commendations",
    18: "transmutation_charges",
    19: "airship_parts",
    20: "ley_line_crystals",
    22: "lumps_of_aurillium",
    23: "spirit_shards",
    24: "pristine_fractal_relics",
    25: "geodes",
    26: "wvw_tickets",
    27: "bandit_crests",
    28: "magnetite_shards",
    29: "provisioner_tokens",
    30: "pvp_league_tickets",
    31: "proof_heroics",
    32: "unbound_magic",
    33: "ascended_shards_of_glory",
    34: "trade_contracts",
    35: "elegy_mosaics",
    36: "test_heroics",
    37: "exalted_keys",
    38: "machetes",
    39: "gaeting_crystals",
    40: "bandit_skeleton_keys",
    41: "pact_crowbars",
    42: "vials_of_chak_acid",
    43: "zephyrite_lockpicks",
    44: "traders_keys",
    45: "volatile_magic",
    46: "pvp_tournament_vouchers",
    47: "racing_medallions",
    49: "mistborn_keys",
    50: "festival_tokens",
    51: "cache_keys",
    52: "red_prophet_shards",
    53: "green_prophet_shards",
    54: "blue_prophet_crystals",
    55: "green_prophet_crystals",
    56: "red_prophet_crystals",
    57: "blue_prophet_shards",
    58: "war_supplies",
    59: "unstable_fractal_essences",
    60: "tyrian_defense_seals",
    61: "research_notes",
    62: "unusual_coins",
    63: "astral_acclaim",
    64: "jade_slivers",
    65: "testimony_of_jade_heroics",
    66: "ancient_coins",
    67: "canach_coins",
    68: "imperial_favors",
    69: "tales_of_dungeon_delving",
    70: "legendary_insights",
    71: "jade_miner_keycards",
    72: "static_charges",
    73: "pinch_of_stardust",
    74: "unnamed_currency_74",
    75: "calcified_gasps",
    76: "ursus_oblige",
    77: "gaeting_crystals_2",
    78: "fine_rift_essences",
    79: "rare_rift_essences",
    80: "masterwork_rift_essences",
    81: "antiquated_ducats",
    82: "testimony_of_castoran_heroics",
    83: "aether_rich_sap",
}

# Human-readable display names for wallet currencies
WALLET_DISPLAY_NAMES: Final[dict[str, str]] = {
    "gold": "Gold",
    "karma": "Karma",
    "laurels": "Laurels",
    "gems": "Gems",
    "ascalonian_tears": "Ascalonian Tears",
    "shards_of_zhaitan": "Shards of Zhaitan",
    "fractal_relics": "Fractal Relics",
    "seals_of_beetletun": "Seals of Beetletun",
    "manifesto_of_the_moletariate": "Manifesto of the Moletariate",
    "deadly_blooms": "Deadly Blooms",
    "symbols_of_koda": "Symbols of Koda",
    "flame_legion_charr_carvings": "Flame Legion Charr Carvings",
    "knowledge_crystals": "Knowledge Crystals",
    "badges_honor": "Badges of Honor",
    "guild_commendations": "Guild Commendations",
    "transmutation_charges": "Transmutation Charges",
    "airship_parts": "Airship Parts",
    "ley_line_crystals": "Ley Line Crystals",
    "lumps_of_aurillium": "Lumps of Aurillium",
    "spirit_shards": "Spirit Shards",
    "pristine_fractal_relics": "Pristine Fractal Relics",
    "geodes": "Geodes",
    "wvw_tickets": "WvW Skirmish Tickets",
    "bandit_crests": "Bandit Crests",
    "magnetite_shards": "Magnetite Shards",
    "provisioner_tokens": "Provisioner Tokens",
    "pvp_league_tickets": "PvP League Tickets",
    "proof_heroics": "Proof of Heroics",
    "unbound_magic": "Unbound Magic",
    "ascended_shards_of_glory": "Ascended Shards of Glory",
    "trade_contracts": "Trade Contracts",
    "elegy_mosaics": "Elegy Mosaics",
    "test_heroics": "Testimony of Desert Heroics",
    "exalted_keys": "Exalted Keys",
    "machetes": "Machetes",
    "gaeting_crystals": "Gaeting Crystals",
    "bandit_skeleton_keys": "Bandit Skeleton Keys",
    "pact_crowbars": "Pact Crowbars",
    "vials_of_chak_acid": "Vials of Chak Acid",
    "zephyrite_lockpicks": "Zephyrite Lockpicks",
    "traders_keys": "Trader's Keys",
    "volatile_magic": "Volatile Magic",
    "pvp_tournament_vouchers": "PvP Tournament Vouchers",
    "racing_medallions": "Racing Medallions",
    "mistborn_keys": "Mistborn Keys",
    "festival_tokens": "Festival Tokens",
    "cache_keys": "Cache Keys",
    "red_prophet_shards": "Red Prophet Shards",
    "green_prophet_shards": "Green Prophet Shards",
    "blue_prophet_crystals": "Blue Prophet Crystals",
    "green_prophet_crystals": "Green Prophet Crystals",
    "red_prophet_crystals": "Red Prophet Crystals",
    "blue_prophet_shards": "Blue Prophet Shards",
    "war_supplies": "War Supplies",
    "unstable_fractal_essences": "Unstable Fractal Essences",
    "tyrian_defense_seals": "Tyrian Defense Seals",
    "research_notes": "Research Notes",
    "unusual_coins": "Unusual Coins",
    "astral_acclaim": "Astral Acclaim",
    "jade_slivers": "Jade Slivers",
    "testimony_of_jade_heroics": "Testimony of Jade Heroics",
    "ancient_coins": "Ancient Coins",
    "canach_coins": "Canach Coins",
    "imperial_favors": "Imperial Favors",
    "tales_of_dungeon_delving": "Tales of Dungeon Delving",
    "legendary_insights": "Legendary Insights",
    "jade_miner_keycards": "Jade Miner Keycards",
    "static_charges": "Static Charges",
    "pinch_of_stardust": "Pinch of Stardust",
    "unnamed_currency_74": "Unknown Currency",
    "calcified_gasps": "Calcified Gasps",
    "ursus_oblige": "Ursus Oblige",
    "gaeting_crystals_2": "Gaeting Crystals",
    "fine_rift_essences": "Fine Rift Essences",
    "rare_rift_essences": "Rare Rift Essences",
    "masterwork_rift_essences": "Masterwork Rift Essences",
    "antiquated_ducats": "Antiquated Ducats",
    "testimony_of_castoran_heroics": "Testimony of Castoran Heroics",
    "aether_rich_sap": "Aether-Rich Sap",
}

# Mapping of GW2 API achievement IDs to WvW stat names
ACHIEVEMENT_MAPPING: Final[dict[int, str]] = {
    283: "players",
    285: "yaks_scorted",
    288: "yaks",
    291: "camps",
    294: "castles",
    297: "towers",
    300: "keeps",
}
